import "./globals.css";
import React from "react";
import {Roboto} from "next/dist/compiled/@next/font/dist/google";

const roboto = Roboto({ weights: [400, 500] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                {children}
            </body>
        </html>
    );
}
